#!/usr/bin/env bash

## Update and install nginx
#sudo apt-get update -y
#sudo apt-get upgrade -y
#sudo apt-get install nginx -y

## Create a folders
sudo mkdir -p /data/web_static/releases/test /data/web_static/shared

## Create a file index.html
sudo chown -R ubuntu:ubuntu /data
sudo echo "Hello world" > /data/web_static/releases/test/index.html

## Create a simbolink link
sudo ln -sf /data/web_static/releases/test/ /data/web_static/current

## Update the nginx configuration
new_string="a location \/hbnb_static\/ {\n\t\talias /data/web_static/current/;\n\t}\n"
sudo sed -i "/server_name _;/$new_string" /etc/nginx/sites-available/default

## Owner and group belong to ubuntu user
sudo chown -R ubuntu:ubuntu /data

## Restarting the nginx service
sudo service nginx restart
